FROM golang:1.23-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/access-api ./cmd/access-api

FROM alpine:3.20
WORKDIR /app
COPY --from=build /out/access-api /app/access-api
COPY migrations /app/migrations
COPY deployments/docker/keys /app/deployments/docker/keys
EXPOSE 8080
CMD ["/app/access-api"]
