FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/scanner-gateway ./cmd/scanner-gateway

FROM alpine:3.20
WORKDIR /app
COPY --from=build /out/scanner-gateway /app/scanner-gateway
COPY web /app/web
COPY deployments/docker/keys /app/deployments/docker/keys
EXPOSE 8081
CMD ["/app/scanner-gateway"]

